{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lightrag.fullname" . }}-rag-storage
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.ragStorage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lightrag.fullname" . }}-inputs
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.inputs.size }}
{{- end }}
