apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: kube-system
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
  POSTGRES_WORKSPACE: default
  PGDATA: /var/lib/postgresql/data/pgdata
  postgresql.conf: |
    shared_preload_libraries = 'vector'
