helm upgrade --install lightrag -f ./values.yaml ../../k8s-deploy/lightrag/ \
	--namespace kube-system \
	--set-string env.AUTH_ACCOUNTS="$AUTH_ACCOUNTS" \
	--set-string env.POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
	--set-string env.NEO4J_PASSWORD=$NEO4J_PASSWORD \
	--set-string env.LLM_BINDING=openai \
	--set-string env.LLM_MODEL=qwen-plus \
	--set-string env.LLM_BINDING_HOST=$LLM_BINDING_HOST \
	--set-string env.LLM_BINDING_API_KEY=$LLM_BINDING_API_KEY \
	--set-string env.EMBEDDING_BINDING=openai \
	--set-string env.EMBEDDING_MODEL=text-embedding-v4 \
	--set-string env.EMBEDDING_DIM=1024 \
	--set-string env.EMBEDDING_BINDING_API_KEY=$EMBEDDING_BINDING_API_KEY
