apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lightrag-linera-respeer-master-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
